import type { Migration } from '../migrator';

/**
 * Migration 001 — initial local schema.
 *
 * Creates the nine core tables listed in docs/database.md §4. Conventions,
 * and the reasoning behind the ones the documentation left open:
 *
 * - Identifiers are TEXT UUIDs (docs/database.md §5). They are generated by
 *   the application, never by the database, so a record keeps the same id
 *   across devices and after synchronization (docs/offline-sync.md §7).
 * - Timestamps are ISO-8601 strings in UTC ("2026-09-09T14:48:00.000Z").
 *   docs/database.md §6 leaves the timezone open; UTC is chosen because a
 *   field device can change timezone between capture and synchronization,
 *   and local-time strings would reorder history when it does. TEXT rather
 *   than INTEGER epoch keeps values readable in a debugger and sorts
 *   correctly with plain lexicographic comparison.
 * - Enumerations are enforced with CHECK constraints (docs/database.md §14).
 *   SQLite has no enum type, and the values must be rejected at the
 *   persistence boundary and not only in application code, since the AI
 *   pipeline is an untrusted producer (CLAUDE.md §7).
 * - Nothing here is deleted. There is no `deleted_at` column anywhere: the
 *   soft-delete strategy is still an open decision (docs/database.md §16)
 *   and adding the column would imply one. It is an additive ALTER TABLE
 *   when the decision is made.
 */
export const migration001: Migration = {
  version: 1,
  name: 'initial-schema',
  up: `
-- ---------------------------------------------------------------------------
-- sites (docs/domain-model.md §4)
-- Created first: users and equipment both reference it.
-- ---------------------------------------------------------------------------
CREATE TABLE sites (
  id          TEXT PRIMARY KEY NOT NULL,
  name        TEXT NOT NULL,
  country     TEXT,
  city        TEXT,
  -- Nullable: a site can be captured by name before its coordinates are
  -- known. Ranges are enforced here because the AI agent is a producer of
  -- these values (docs/ai-agent.md §8, "geographic values").
  latitude    REAL CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
  longitude   REAL CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
  address     TEXT,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- users (docs/domain-model.md §3)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id         TEXT PRIMARY KEY NOT NULL,
  name       TEXT NOT NULL,
  role       TEXT NOT NULL
             CHECK (role IN ('field_user', 'sales', 'medical_staff')),
  -- The user's home site. ON DELETE SET NULL rather than CASCADE: removing a
  -- site must never remove the people who captured data about it.
  site_id    TEXT REFERENCES sites (id) ON DELETE SET NULL,
  city       TEXT,
  country    TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- equipment (docs/domain-model.md §5, docs/database.md §7)
-- One row may represent a group of identical items (docs/domain-model.md §13),
-- which is what 'quantity' is for.
-- ---------------------------------------------------------------------------
CREATE TABLE equipment (
  id                TEXT PRIMARY KEY NOT NULL,
  -- RESTRICT, not CASCADE: deleting a site must not silently destroy the
  -- equipment recorded at it (CLAUDE.md §6, do not silently discard data).
  site_id           TEXT NOT NULL REFERENCES sites (id) ON DELETE RESTRICT,
  brand             TEXT,
  model             TEXT,
  modality          TEXT,
  quantity          INTEGER CHECK (quantity IS NULL OR quantity > 0),
  installation_year INTEGER
                    CHECK (installation_year IS NULL
                           OR (installation_year BETWEEN 1900 AND 2100)),
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- conversations (docs/domain-model.md §10)
-- 'status' values come from docs/ai-agent.md §11.
-- ---------------------------------------------------------------------------
CREATE TABLE conversations (
  id                   TEXT PRIMARY KEY NOT NULL,
  user_id              TEXT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  started_at           TEXT NOT NULL,
  ended_at             TEXT,
  status               TEXT NOT NULL
                       CHECK (status IN ('collecting',
                                         'awaiting_clarification',
                                         'awaiting_confirmation',
                                         'ready_to_save',
                                         'saved',
                                         'failed')),
  -- Pointer to the transcript artifact on the filesystem, not the transcript
  -- itself: transcripts may contain audio-length text and do not belong in a
  -- row that is read on every dashboard query.
  transcript_reference TEXT,
  summary              TEXT,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- observations (docs/domain-model.md §6, docs/database.md §8)
-- An observation is information collected about equipment, never the
-- equipment itself (docs/domain-model.md §5). Observations are append-only:
-- a newer one never deletes an older one (docs/domain-model.md §14).
-- ---------------------------------------------------------------------------
CREATE TABLE observations (
  id                          TEXT PRIMARY KEY NOT NULL,
  -- Nullable on purpose. Capture must not block on resolving which existing
  -- equipment record this observation belongs to (CLAUDE.md §6); duplicate
  -- detection runs after the observation is already safely persisted, and
  -- links it then.
  equipment_id                TEXT REFERENCES equipment (id) ON DELETE RESTRICT,
  site_id                     TEXT NOT NULL REFERENCES sites (id) ON DELETE RESTRICT,
  -- The conversation that produced this observation
  -- (docs/domain-model.md §12). Nullable: an observation may also be entered
  -- through a plain form without the AI agent.
  conversation_id             TEXT REFERENCES conversations (id) ON DELETE SET NULL,
  visit_date                  TEXT NOT NULL,
  quantity                    INTEGER CHECK (quantity IS NULL OR quantity > 0),
  brand                       TEXT,
  model                       TEXT,
  modality                    TEXT,
  estimated_years_of_use      INTEGER
                              CHECK (estimated_years_of_use IS NULL
                                     OR estimated_years_of_use >= 0),
  estimated_installation_year INTEGER
                              CHECK (estimated_installation_year IS NULL
                                     OR (estimated_installation_year
                                         BETWEEN 1900 AND 2100)),
  -- No CHECK constraint: the allowed values for operational status are not
  -- enumerated anywhere in the documentation. docs/ai-agent.md §7 shows only
  -- the value 'unknown'. Left unconstrained rather than inventing a set
  -- (CLAUDE.md §8); add the CHECK in a later migration once defined.
  operational_status          TEXT,
  -- The originating source. The full set of sources contributing to this
  -- observation lives in observation_sources, which must not be overwritten
  -- when information is combined (docs/domain-model.md §9).
  capture_source              TEXT
                              CHECK (capture_source IS NULL
                                     OR capture_source IN ('voice', 'text', 'image')),
  -- Stored in the user's original language, never MedPsy's English working
  -- copy (docs/domain-model.md §6, docs/tech-stack.md §7.2).
  notes                       TEXT,
  -- Derived from the per-attribute values in attribute_confidence by an
  -- explicit business rule (docs/ai-agent.md §9). The rule itself is a
  -- domain concern and is not implemented in this migration.
  overall_confidence          TEXT
                              CHECK (overall_confidence IS NULL
                                     OR overall_confidence IN ('high', 'medium', 'low')),
  created_by                  TEXT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  created_at                  TEXT NOT NULL,
  updated_at                  TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- observation_sources (docs/database.md §4, docs/domain-model.md §9)
-- One row per source that contributed to an observation. Combining
-- information adds rows; it never rewrites existing ones.
-- ---------------------------------------------------------------------------
CREATE TABLE observation_sources (
  id             TEXT PRIMARY KEY NOT NULL,
  observation_id TEXT NOT NULL REFERENCES observations (id) ON DELETE CASCADE,
  source         TEXT NOT NULL CHECK (source IN ('voice', 'text', 'image')),
  -- Filesystem pointer to the captured artifact (the photo, the audio clip),
  -- mirroring conversations.transcript_reference. Without it a photo-sourced
  -- observation cannot be traced back to the photo it came from.
  reference      TEXT,
  created_at     TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- attribute_confidence (docs/database.md §9, docs/domain-model.md §7–§9)
-- Confidence, status and source recorded per attribute, keyed by attribute
-- name so that adding an extracted attribute needs no schema change.
-- ---------------------------------------------------------------------------
CREATE TABLE attribute_confidence (
  id               TEXT PRIMARY KEY NOT NULL,
  observation_id   TEXT NOT NULL REFERENCES observations (id) ON DELETE CASCADE,
  attribute_name   TEXT NOT NULL,
  confidence_level TEXT NOT NULL
                   CHECK (confidence_level IN ('high', 'medium', 'low')),
  attribute_status TEXT NOT NULL
                   CHECK (attribute_status IN ('confirmed', 'reported',
                                               'estimated', 'unknown')),
  source           TEXT CHECK (source IS NULL
                               OR source IN ('voice', 'text', 'image')),
  created_at       TEXT NOT NULL,
  -- One confidence row per attribute per observation. Re-extracting an
  -- attribute updates its row rather than accumulating duplicates.
  UNIQUE (observation_id, attribute_name)
);

-- ---------------------------------------------------------------------------
-- sync_records (docs/domain-model.md §11, docs/database.md §10)
-- Tracks the pending synchronization state of one local entity.
-- ---------------------------------------------------------------------------
CREATE TABLE sync_records (
  id              TEXT PRIMARY KEY NOT NULL,
  entity_type     TEXT NOT NULL
                  CHECK (entity_type IN ('site', 'equipment',
                                         'observation', 'conversation')),
  -- No SQL foreign key: entity_id is polymorphic and points into whichever
  -- table entity_type names. Referential integrity for this column is the
  -- repository layer's responsibility.
  entity_id       TEXT NOT NULL,
  operation       TEXT NOT NULL CHECK (operation IN ('create', 'update', 'delete')),
  sync_status     TEXT NOT NULL
                  CHECK (sync_status IN ('local_only', 'pending', 'syncing',
                                         'synchronized', 'failed', 'conflict')),
  last_attempt_at TEXT,
  last_error      TEXT,
  server_version  INTEGER,
  local_version   INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL,
  -- Idempotency (docs/offline-sync.md §7): exactly one sync record per
  -- entity. Retrying a failed upload updates this row; it never enqueues a
  -- second one, so a retry cannot create a duplicate on the server.
  UNIQUE (entity_type, entity_id)
);

-- ---------------------------------------------------------------------------
-- map_regions (docs/database.md §4, docs/offline-sync.md §11–§12)
-- Local cache state of downloaded map resources ONLY. Downloading a region
-- does not download business data, and this table must never be read as a
-- statement about which sites or equipment are available offline.
-- ---------------------------------------------------------------------------
CREATE TABLE map_regions (
  id                TEXT PRIMARY KEY NOT NULL,
  name              TEXT NOT NULL,
  min_latitude      REAL NOT NULL CHECK (min_latitude BETWEEN -90 AND 90),
  max_latitude      REAL NOT NULL CHECK (max_latitude BETWEEN -90 AND 90),
  min_longitude     REAL NOT NULL CHECK (min_longitude BETWEEN -180 AND 180),
  max_longitude     REAL NOT NULL CHECK (max_longitude BETWEEN -180 AND 180),
  download_status   TEXT NOT NULL
                    CHECK (download_status IN ('not_downloaded', 'downloading',
                                               'downloaded', 'failed')),
  download_progress REAL NOT NULL DEFAULT 0
                    CHECK (download_progress BETWEEN 0 AND 1),
  last_error        TEXT,
  size_bytes        INTEGER CHECK (size_bytes IS NULL OR size_bytes >= 0),
  downloaded_at     TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  CHECK (min_latitude <= max_latitude),
  CHECK (min_longitude <= max_longitude)
);

-- ---------------------------------------------------------------------------
-- Indexes (docs/database.md §13)
-- The first seven are the candidates the documentation names. The rest cover
-- foreign keys that are read as parent -> children on a hot path; SQLite does
-- not index foreign keys automatically, and without these every dashboard or
-- detail screen degrades into a table scan as the local dataset grows.
-- ---------------------------------------------------------------------------
CREATE INDEX idx_sites_name                    ON sites (name);
CREATE INDEX idx_sites_country                 ON sites (country);
CREATE INDEX idx_sites_city                    ON sites (city);
CREATE INDEX idx_equipment_site_id             ON equipment (site_id);
CREATE INDEX idx_observations_equipment_id     ON observations (equipment_id);
CREATE INDEX idx_observations_visit_date       ON observations (visit_date);
CREATE INDEX idx_sync_records_sync_status      ON sync_records (sync_status);

-- Site detail and map popups list observations for a site.
CREATE INDEX idx_observations_site_id          ON observations (site_id);
-- Reviewing what a conversation produced before saving.
CREATE INDEX idx_observations_conversation_id  ON observations (conversation_id);
-- Loading an observation always loads its sources and confidence rows.
CREATE INDEX idx_observation_sources_obs_id    ON observation_sources (observation_id);
CREATE INDEX idx_attribute_confidence_obs_id   ON attribute_confidence (observation_id);
-- Conversation list for the current user.
CREATE INDEX idx_conversations_user_id         ON conversations (user_id);
-- Resolving a sync response back to its local record.
CREATE INDEX idx_sync_records_entity           ON sync_records (entity_type, entity_id);
`,
};
